[2025-05-14T05:10:49.151+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: ecommerce_data_ingestion.wait_for_add_to_carts manual__2025-05-14T05:10:33.646290+00:00 [queued]>
[2025-05-14T05:10:49.182+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: ecommerce_data_ingestion.wait_for_add_to_carts manual__2025-05-14T05:10:33.646290+00:00 [queued]>
[2025-05-14T05:10:49.184+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 2
[2025-05-14T05:10:49.622+0000] {taskinstance.py:2191} INFO - Executing <Task(FileSensor): wait_for_add_to_carts> on 2025-05-14 05:10:33.646290+00:00
[2025-05-14T05:10:49.647+0000] {standard_task_runner.py:60} INFO - Started process 109 to run task
[2025-05-14T05:10:49.670+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'ecommerce_data_ingestion', 'wait_for_add_to_carts', 'manual__2025-05-14T05:10:33.646290+00:00', '--job-id', '105', '--raw', '--subdir', 'DAGS_FOLDER/ecommerce_etl_dag.py', '--cfg-path', '/tmp/tmpd1wt5wk6']
[2025-05-14T05:10:49.682+0000] {standard_task_runner.py:88} INFO - Job 105: Subtask wait_for_add_to_carts
[2025-05-14T05:10:49.827+0000] {task_command.py:423} INFO - Running <TaskInstance: ecommerce_data_ingestion.wait_for_add_to_carts manual__2025-05-14T05:10:33.646290+00:00 [running]> on host 1e43c0d7b523
[2025-05-14T05:10:49.971+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='ecommerce_data_ingestion' AIRFLOW_CTX_TASK_ID='wait_for_add_to_carts' AIRFLOW_CTX_EXECUTION_DATE='2025-05-14T05:10:33.646290+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-05-14T05:10:33.646290+00:00'
[2025-05-14T05:10:49.976+0000] {connection.py:473} ERROR - Unable to retrieve connection from secrets backend (EnvironmentVariablesBackend). Checking subsequent secrets backend.
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/connection.py", line 468, in get_connection_from_secrets
    conn = secrets_backend.get_connection(conn_id=conn_id)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/secrets/base_secrets.py", line 96, in get_connection
    value = self.get_conn_value(conn_id=conn_id)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/secrets/environment_variables.py", line 51, in get_conn_value
    return os.environ.get(CONN_ENV_PREFIX + conn_id.upper())
AttributeError: 'NoneType' object has no attribute 'upper'
[2025-05-14T05:10:50.046+0000] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/sensors/base.py", line 265, in execute
    raise e
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/sensors/base.py", line 247, in execute
    poke_return = self.poke(context)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/sensors/filesystem.py", line 63, in poke
    hook = FSHook(self.fs_conn_id)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/hooks/filesystem.py", line 64, in __init__
    conn = self.get_connection(fs_conn_id)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/hooks/base.py", line 82, in get_connection
    conn = Connection.get_connection_from_secrets(conn_id)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/connection.py", line 479, in get_connection_from_secrets
    raise AirflowNotFoundException(f"The conn_id `{conn_id}` isn't defined")
airflow.exceptions.AirflowNotFoundException: The conn_id `None` isn't defined
[2025-05-14T05:10:50.053+0000] {taskinstance.py:1138} INFO - Marking task as UP_FOR_RETRY. dag_id=ecommerce_data_ingestion, task_id=wait_for_add_to_carts, execution_date=20250514T051033, start_date=20250514T051049, end_date=20250514T051050
[2025-05-14T05:10:50.116+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 105 for task wait_for_add_to_carts (The conn_id `None` isn't defined; 109)
[2025-05-14T05:10:50.131+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2025-05-14T05:10:50.183+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
