[2025-05-14T03:54:51.406+0000] {scheduler_job_runner.py:781} ERROR - Executor reports task instance <TaskInstance: ecommerce_data_ingestion.wait_for_add_to_carts scheduled__2025-05-13T01:00:00+00:00 [queued]> finished (failed) although the task says it's queued. (Info: None) Was the task killed externally?
