[2025-06-09T05:49:23.036+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: kafka_ecommerce_pipeline.run_kafka_consumer scheduled__2025-06-09T05:40:00+00:00 [queued]>
[2025-06-09T05:49:23.040+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: kafka_ecommerce_pipeline.run_kafka_consumer scheduled__2025-06-09T05:40:00+00:00 [queued]>
[2025-06-09T05:49:23.040+0000] {taskinstance.py:2170} INFO - Starting attempt 3 of 3
[2025-06-09T05:49:23.046+0000] {taskinstance.py:2191} INFO - Executing <Task(BashOperator): run_kafka_consumer> on 2025-06-09 05:40:00+00:00
[2025-06-09T05:49:23.049+0000] {standard_task_runner.py:60} INFO - Started process 602 to run task
[2025-06-09T05:49:23.052+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'kafka_ecommerce_pipeline', 'run_kafka_consumer', 'scheduled__2025-06-09T05:40:00+00:00', '--job-id', '29', '--raw', '--subdir', 'DAGS_FOLDER/kafka_data_pipeline.py', '--cfg-path', '/tmp/tmps0c2eb22']
[2025-06-09T05:49:23.053+0000] {standard_task_runner.py:88} INFO - Job 29: Subtask run_kafka_consumer
[2025-06-09T05:49:23.086+0000] {task_command.py:423} INFO - Running <TaskInstance: kafka_ecommerce_pipeline.run_kafka_consumer scheduled__2025-06-09T05:40:00+00:00 [running]> on host 045789bdf773
[2025-06-09T05:49:23.137+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='data-engineering-team' AIRFLOW_CTX_DAG_ID='kafka_ecommerce_pipeline' AIRFLOW_CTX_TASK_ID='run_kafka_consumer' AIRFLOW_CTX_EXECUTION_DATE='2025-06-09T05:40:00+00:00' AIRFLOW_CTX_TRY_NUMBER='3' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-06-09T05:40:00+00:00'
[2025-06-09T05:49:23.138+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-06-09T05:49:23.139+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'cd /opt/***/ecom_etl/ && python kafka_scripts/consumer.py']
[2025-06-09T05:49:23.147+0000] {subprocess.py:86} INFO - Output:
[2025-06-09T05:49:23.344+0000] {subprocess.py:93} INFO - üöÄ Starting E-Commerce Event Consumer
[2025-06-09T05:49:23.345+0000] {subprocess.py:93} INFO - üîó Kafka: kafka:29092
[2025-06-09T05:49:23.345+0000] {subprocess.py:93} INFO - üî¥ Redis: redis:6379
[2025-06-09T05:49:23.345+0000] {subprocess.py:93} INFO - ‚ùå Error initializing consumer: 'ECommerceEventConsumer' object has no attribute 'bootstrap_servers'
[2025-06-09T05:49:23.345+0000] {subprocess.py:93} INFO - ‚ùå Error in main: 'ECommerceEventConsumer' object has no attribute 'bootstrap_servers'
[2025-06-09T05:49:23.345+0000] {subprocess.py:93} INFO - Traceback (most recent call last):
[2025-06-09T05:49:23.345+0000] {subprocess.py:93} INFO -   File "kafka_scripts/consumer.py", line 462, in <module>
[2025-06-09T05:49:23.345+0000] {subprocess.py:93} INFO -     main()
[2025-06-09T05:49:23.346+0000] {subprocess.py:93} INFO -   File "kafka_scripts/consumer.py", line 452, in main
[2025-06-09T05:49:23.346+0000] {subprocess.py:93} INFO -     consumer = ECommerceEventConsumer()
[2025-06-09T05:49:23.346+0000] {subprocess.py:93} INFO -   File "kafka_scripts/consumer.py", line 56, in __init__
[2025-06-09T05:49:23.346+0000] {subprocess.py:93} INFO -     bootstrap_servers=self.bootstrap_servers,
[2025-06-09T05:49:23.346+0000] {subprocess.py:93} INFO - AttributeError: 'ECommerceEventConsumer' object has no attribute 'bootstrap_servers'
[2025-06-09T05:49:23.373+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2025-06-09T05:49:23.380+0000] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 428, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/bash.py", line 212, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2025-06-09T05:49:23.381+0000] {taskinstance.py:1138} INFO - Marking task as FAILED. dag_id=kafka_ecommerce_pipeline, task_id=run_kafka_consumer, execution_date=20250609T054000, start_date=20250609T054923, end_date=20250609T054923
[2025-06-09T05:49:23.387+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 29 for task run_kafka_consumer (Bash command failed. The command returned a non-zero exit code 1.; 602)
[2025-06-09T05:49:23.400+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2025-06-09T05:49:23.419+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
