[2025-06-09T10:51:25.494+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: kafka_ecommerce_pipeline.verify_pipeline_results manual__2025-06-09T10:47:20.305214+00:00 [queued]>
[2025-06-09T10:51:25.502+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: kafka_ecommerce_pipeline.verify_pipeline_results manual__2025-06-09T10:47:20.305214+00:00 [queued]>
[2025-06-09T10:51:25.502+0000] {taskinstance.py:2170} INFO - Starting attempt 2 of 4
[2025-06-09T10:51:25.512+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): verify_pipeline_results> on 2025-06-09 10:47:20.305214+00:00
[2025-06-09T10:51:25.519+0000] {standard_task_runner.py:60} INFO - Started process 318 to run task
[2025-06-09T10:51:25.523+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'kafka_ecommerce_pipeline', 'verify_pipeline_results', 'manual__2025-06-09T10:47:20.305214+00:00', '--job-id', '16', '--raw', '--subdir', 'DAGS_FOLDER/kafka_data_pipeline.py', '--cfg-path', '/tmp/tmpmajk9liw']
[2025-06-09T10:51:25.524+0000] {standard_task_runner.py:88} INFO - Job 16: Subtask verify_pipeline_results
[2025-06-09T10:51:25.561+0000] {task_command.py:423} INFO - Running <TaskInstance: kafka_ecommerce_pipeline.verify_pipeline_results manual__2025-06-09T10:47:20.305214+00:00 [running]> on host ffaec3049530
[2025-06-09T10:51:25.609+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='data-engineering-team' AIRFLOW_CTX_DAG_ID='kafka_ecommerce_pipeline' AIRFLOW_CTX_TASK_ID='verify_pipeline_results' AIRFLOW_CTX_EXECUTION_DATE='2025-06-09T10:47:20.305214+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-06-09T10:47:20.305214+00:00'
[2025-06-09T10:51:25.610+0000] {kafka_data_pipeline.py:133} INFO - ✅ Verifying pipeline results in Redis...
[2025-06-09T10:51:25.612+0000] {kafka_data_pipeline.py:168} ERROR - ❌ Error verifying pipeline results: Total views not found or 0 in Redis - data pipeline might have issues.
[2025-06-09T10:51:25.620+0000] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 428, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 199, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 216, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/kafka_data_pipeline.py", line 142, in verify_pipeline_results
    raise AirflowException("Total views not found or 0 in Redis - data pipeline might have issues.")
airflow.exceptions.AirflowException: Total views not found or 0 in Redis - data pipeline might have issues.
[2025-06-09T10:51:25.623+0000] {taskinstance.py:1138} INFO - Marking task as UP_FOR_RETRY. dag_id=kafka_ecommerce_pipeline, task_id=verify_pipeline_results, execution_date=20250609T104720, start_date=20250609T105125, end_date=20250609T105125
[2025-06-09T10:51:25.630+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 16 for task verify_pipeline_results (Total views not found or 0 in Redis - data pipeline might have issues.; 318)
[2025-06-09T10:51:25.661+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2025-06-09T10:51:25.677+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
